name: my_words
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^0.8.4
  share_plus: ^7.2.2
  path_provider: ^2.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_gen_runner: ^5.3.0
  google_fonts: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  change_app_package_name: ^1.1.0
  screenshot: ^2.4.0
  flutter_animation_progress_bar: ^2.3.1
  pdf: ^3.11.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  flutter_screenutil: ^5.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"

flutter_native_splash:
  image: "assets/images/Wor.png"
  color: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
